### PR TITLE
[FEAT] Add a project to demonstrate integration with Parcel

### PR DESCRIPTION
**Pull request by tbouffard**
Use Parcel v2.

### Rationale

I added this project to ensure the lib is working with more bundlers or build tools. In the past, we detected issues with ViteJS but not with Rollup. I think having more examples will help us catch problems earlier.

More examples may increase the maintenance tasks. Today, we don't have to change the existing projects very often. Let's recheck this in a few months.

Covers #20

### CODE REVIEW

**Review by csouchet — CHANGES_REQUESTED** [review]
I have the loop error 🙁 
image

> _**Note**_
Same error on CI https://github.com/process-analytics/bpmn-visualization-examples/runs/6705693125?check_suite_focus=true



I saw there is a new version of Parcel (2.6.0). I will try with it.

**Comment by csouchet** [comment]
With the version `2.6.0` of `Parcel`:
image

**Comment by tbouffard** [comment]
:-( this is weird. The initial commit d56b4b8 was passing (https://github.com/process-analytics/bpmn-visualization-examples/actions/runs/2369213459) and in the latest commit, we are still using bpmn-visualization@0.23.3

**Comment by tbouffard** [comment]
I have just redo the worklow run of commit d56b4b8 and now I see the issue
https://github.com/process-analytics/bpmn-visualization-examples/runs/6706157202?check_suite_focus=true

Someone has the same problem: https://github.com/parcel-bundler/parcel/issues/6675#issuecomment-1142543744

**Comment by tbouffard** [comment]
@csouchet I guess I found a way to make parcel display the diagram by configuring an alias in the package.json file, and force it to use the bpmn-visualization ESM bundle.
I found this setting in https://codesandbox.io/s/bpmn-visualization-ts-sandbox-erkrbc?file=/package.json:342-437, which is set when create a CodeSandbox project with the parcel environment that powers the vanilla-ts codesanbox template.

I am not sure why parcel would use by default the commonjs bundle, perhaps like webpack does (we have a specific setting for wepack as well to ensure it uses the ESM bundle,  see https://github.com/process-analytics/bpmn-visualization-examples/blob/v0.24.0/projects/javascript-vanilla-with-webpack/webpack.config.js#L21-L26

So this is an additional arguments to remove the CommonJS bundle from the npm package

**Review by csouchet — APPROVED** [review]
It works fine with the last changes.

**Pull request merged**
