### PR TITLE
[DIAGRAM] Introduce Vertical & Horizontal Pools with Sub-Lane

### PR DESCRIPTION
**Pull request by csouchet**
Relates to https://github.com/process-analytics/bpmn-visualization-js/pull/573

### CODE REVIEW

**Comment by aibcmars** [comment]
I don't understand why do we have the .png files here (bpmn-files/pools__bpmn-visualization-0.2.0-dev.png and 0.3.0) ?
normally there is only  file.bpmn and corresponding file__bpmn.svg

**Comment by tbouffard** [comment]
> I don't understand why do we have the .png files here (bpmn-files/pools__bpmn-visualization-0.2.0-dev.png and 0.3.0) ?
> normally there is only file.bpmn and corresponding file__bpmn.svg

I guess, here we don't do the screenshot using bpmn-js but with our lib :smile:

**Comment by csouchet** [comment]
Yes, I see we did that before, because the vertical mode is not supported by BPMN.io

**Comment by aibcmars** [comment]
thx for clarifying :)

**Review by aibcmars — APPROVED** [review]
LGTM

**Pull request merged**
