### PR TITLE
[FEAT] Improve the visualization of the diagram paths on the Frequency/Time Demo

### PR DESCRIPTION
**Pull request by VishalThapaliya**

### CODE REVIEW

**Comment by csouchet** [comment]
@VishalThapaliya Thank you very much for your contribution 🙂 

Firstly, you need to accept the CLA. Without that, we can't merge your PR 🙁

**Comment by csouchet** [comment]
Secondly, with your modifications, there is no more the difference of thickness of the lines according to the scale. This is a regression 🙁

**Review by csouchet — CHANGES_REQUESTED** [review]
With your modifications, there is no more the difference of thickness of the lines according to the scale. This is a regression 🙁 

| Before | Now | 
|-------|------|
|image|image|

**Comment by tbouffard** [comment]
@VishalThapaliya any news on this? otherwise we will close this PR

**Comment by tbouffard** [comment]
No activity so I am closing this Pull Request.
Feel free to reopen it or comment if you have news.

**Pull request closed without merging**
