### PR TITLE
[FEAT] Add a tool to compare BPMN rendering from version to version

### PR DESCRIPTION
**Pull request by tbouffard**
It let generate screenshots of the B.2.0 rendering from version 0.1.0 to version
0.10.0 and see the evolution of the BPMN support in `bpmn-visualization`.

**Live environment of examples**

https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bpmn-visu_versions_rendering_comparison/examples/index.html

### CODE REVIEW

**Comment by tbouffard** [comment]
❓ I am no more sure that this tool should be store in this repository but probably in a dedicated repository.
It is not an example of usage of the lib, it introduce a lot of large files in the repository.
It probably deserve its own repository or to be store in a repository that would store tooling about our ability to render diagram for demonstration purpose.
This repository may include tooling to check our ability to correctly render `miwg-test-suite` BPMN diagrams prior submitting results.

**Comment by csouchet** [comment]
I think it's a good idea to put it in a dedicated repository 🙂

**Comment by tbouffard** [comment]
Converted to draft as we don't want to merge it in the repository. It will be closed when the integrated in the new 'tooling' repository

**Comment by tbouffard** [comment]
Closing, it will be integrated in the tools repository: https://github.com/process-analytics/bpmn-visualization-tools/pull/1

**Pull request closed without merging**
